title: Daniele Laporta
#logo: image.png
description: Played Football for 15 years in a team, always enjoying any sporty challenge, tech passionate and love travelling!
#show_downloads: true
theme: jekyll-theme-minimal
