title: Daniele Laporta
logo: ![logo](/assets/img/model.png)
description: Unlocking insights, driving innovation. Tech passionate and love travelling!

#show_downloads: true
theme: jekyll-theme-minimal
